layerrules = true
kill_bind = "ctrl+shift+alt, h"
version = 2

[windows]
scale = 8.5
items_per_row = 5

[windows.overview]
key = "x"
modifier = "super"
filter_by = []
hide_filtered = false

[windows.overview.launcher]
default_terminal = "ghostty"
launch_modifier = "ctrl"
width = 650
max_items = 5
show_when_empty = true

[windows.overview.launcher.plugins.applications]
run_cache_weeks = 4
show_execs = true
show_actions_submenu = true

[windows.overview.launcher.plugins.terminal]

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://duckduckgo.com/?q={}"
name = "DuckDuckGo"
key = "d"

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://www.youtube.com/results?search_query={}"
name = "YouTube"
key = "y"

[[windows.overview.launcher.plugins.websearch.engines]]
url = "https://wiki.archlinux.org/index.php?search={}"
name = "ArchWiki"
key = "a"

[windows.overview.launcher.plugins.calc]

[windows.overview.launcher.plugins.path]
