layerrules = true
kill_bind = "ctrl+shift+alt, h"
version = 1

[windows]
scale = 8.5
items_per_row = 5

[windows.overview]
modifier = "super"
key = "x"

[windows.overview.launcher]
default_terminal = "ghostty"

[windows.overview.launcher.plugins]
terminal = {}
applications = {}
calc = {}
path  = {}

[windows.overview.launcher.plugins.websearch]
engines = [
  { url = "https://duckduckgo.com/?q={}", name = "DuckDuckGo", key = "d" },
  { url = "https://www.youtube.com/results?search_query={}", name = "YouTube", key = "y" },
  { url = "https://wiki.archlinux.org/index.php?search={}", name = "ArchWiki", key = "a" }
]
